name: Run K6 Load Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do c贸digo
        uses: actions/checkout@v3

      - name: Instalar K6 via snap
        run: sudo snap install k6

      - name: Criar diret贸rio de relat贸rios
        run: mkdir -p reports/logs

      - name: Executar testes de carga com K6
        run: k6 run scripts/placeholder/resources.js --vus 5 --duration 10s --out json=reports/test_$(date +%Y%m%d_%H%M%S).json

      - name: Upload de relat贸rios
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: k6-reports
          path: reports/**/*
